apiVersion: v1
kind: Service
metadata:
  name: admin-ui-nodeport
  labels:
    app: admin-ui-nodeport
spec:
  type: NodePort
  ports:
  - name: admin-ui
    protocol: TCP
    #port is loadbalancer port
    port: 8080
    # targetport is container port
    targetPort: 80
    nodePort: 32014
  selector:
    app: admin-ui
