apiVersion: v1
kind: Service
metadata:
  name: emotibot-controller-20-nodeport
  labels:
    app: emotibot-controller-20-nodeport
spec:
  type: NodePort
  ports:
  - name: emotibot-controller-20
    protocol: TCP
    #port is loadbalancer port
    port: 8080
    # targetport is container port
    targetPort: 8080
    nodePort: 32013
  selector:
    app: emotibot-controller-20
