apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      # soft antiaffinity for optimize placement
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - phpmyadmin
              topologyKey: kubernetes.io/hostname
      containers:
      - name: phpmyadmin
        image: 172.16.101.70/suse_image/phpmyadmin:release
        env:
        - name: PMA_HOST
          value: "mysql"      
        volumeMounts:
        - mountPath: /etc/localtime
          name: hosttime
      volumes:
       - name: hosttime
         hostPath:
           path: /etc/localtime 
      #select node label if enable
      #nodeSelector:
      #  ebotrole: worker
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
  - name: http
    protocol: TCP
    #port is loadbalancer port
    port: 8080
    # targetport is container port
    targetPort: 80
  selector:
    app: phpmyadmin
