apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-nodeport
  labels:
    app: phpmyadmin-nodeport
spec:
  type: NodePort
  ports:
  - name: phpmyadmin
    protocol: TCP
    #port is loadbalancer port
    port: 8080
    # targetport is container port
    targetPort: 80
    nodePort: 31180
  selector:
    app: phpmyadmin
