apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  labels:
    app: mysql-nodeport
spec:
  type: NodePort
  ports:
  - name: mysql
    protocol: TCP
    #port is loadbalancer port
    port: 3306
    # targetport is container port
    targetPort: 3306
    nodePort: 30084
  selector:
    app: mysql
