apiVersion: v1
kind: Service
metadata:
  name: solr-nodeport
  labels:
    app: solr-nodeport
spec:
  type: NodePort
  ports:
  - name: solr
    protocol: TCP
    port: 8081
    targetPort: 8983
    nodePort: 30099
  selector:
    app: solrsiang
