apiVersion: v1
kind: ConfigMap
metadata:
  name: csbot-env
data:

  DECRYPTION_SERVICE: "admin-ui:8080/api/v1/ui/decrypt?text="
# ==================================================================
# multicustomer
# ==================================================================
  MC_HTTP_SERVER_PORT: "8080"
  MC_PROCESS_DATA_URI: "process_data"
  MC_PROCESS_ROBOT_CONFIG_URI: "robot_config"
  MC_PROCESS_KNOWLEDGE_URI: "knowledge"
  MC_PROCESS_ENTITY_URI: "entity"
  MC_GET_ENTITY_LIST_URI: "entities"
  MC_ROLLBACK_DATA_URI: "rollback"
  MC_DOWNLOAD_DATA_URI: "download"
  MC_PROCESS_INTENT_URI: "intent"
  MC_PROCESS_MANUAL_EDIT_URI: "manual_edit"
  MC_PROCESS_BACKFILL_URI: "backfill"
  MC_PROCESS_BUSINESS_URI: "business"
  MC_PROCESS_BUSINESS_MANUAL_URI: "manual_business"
  MC_PROCESS_ALGORITHM_URI: "algorithm"
  MC_PROCESS_MANUAL_ENTITY_URI: "manual_entity"
  MC_DATA_ACCESS_URI: "dao"
  MC_CONSUL_DATA_PROCESS_URI: "consul_data"
  MC_CUSTOMER_APPID_BASEPATH: "/usr/src/multicustomer/csv/"

#mysql emoticon information
  MC_MYSQL_HOST: "mysql:3306"
  MC_MYSQL_DATABASE: "emotibot"
  MC_MYSQL_USER: "root"
  MC_MYSQL_PASS: "b/ixGYSvx8c9bmAapWkZcw=="

#audit mysql information
  MC_AUDIT_DB_HOST: "mysql:3306"
  MC_AUDIT_DB_NAME: "emotibot"
  MC_AUDIT_DB_ACCOUNT: "root"
  MC_AUDIT_DB_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="

  #MC_ROBOT_PROP_TRIGGER_SERVICE=http://172.17.0.1:11601/robot?
  MC_SOLR_POST_FILE_FULL_SERVICE: "http://solr-etl-agent:8080/editorial"
  MC_SOLR_POST_FILE_INCRE_SERVICE: "http://solr-etl-agent:8080/editorialincre"
  MC_SOLR_POST_FILE_INTENT_SERVICE: "http://solr-etl-agent:8080/3rd/intent"
  MC_SOLR_POST_FILE_REMOVE_SERVICE: "http://solr-etl-agent:8080/editorial/deletebyids"
  MC_SOLR_GET_IDS_REMOVE_SERVICE: "http://solr-etl-agent:8080/deletebyids?ids="
  MC_SOLR_GET_FIELD_REMOVE_SERVICE: "http://solr-etl-agent:8080/editorial/deletebyquery?"

# for platform_schedule.sh
  MC_PROCESS_MANUAL_SCHEDULE_SERVICE: "http://localhost:8080/manual_edit"
  MC_PROCESS_BUSINESS_MANUAL_SCHEDULE_SERVICE: "http://localhost:8080/manual_business"
  MC_PROCESS_ENTITY_MANUAL_SCHEDULE_SERVICE: "http://localhost:8080/manual_entity"

  MC_NLU_SERVICE: "http://snlu-all:8080/?"
  MC_SENTENCE_TYPE_SERVICE: "http://172.17.0.1:12001/ai/simpleChat?id=sentence_type&input="
  
  MC_CONSUL_URL: "http://consul:8500/v1/kv/idc/"
  MC_WGET_FILE_PATH: "http://172.17.0.1/Files/settings/"
  MC_ENVIRONMENT: "dev"
  MC_ENTITY_MAX_LIMIT: "100000"
  MC_ENTITY_SIMILAR_MAX_LIMIT: "50000"
  MC_Houta_FILE_PATH: "/home/deployer/infrastructure/volumes/houta/Files"

# ==================================================================
# faq-module-20
# ==================================================================
  FAQ_MODULE_NAME: "FAQ-Module"
  FAQ_HOME_DIR: "/usr/src/app"
  FAQ_PORT: "8080"
  FAQ_HOST_LOGGER_FILE_DIR: "/home/deployer/debug_logs/logs/faq_logs"
  FAQ_LOGGER_FILE_DIR: "/var/log/FAQModule2.0"
  FAQ_TIMEOUT: "200"
  FAQ_MAX_THREAD: "100"
  MODULE_LOG_LEVEL: "0"
  FAQ_ML_SERVICE_ADDR: ""
  ML_CANDIDATE_SIZE: "5"
  FAQ_SE_SERVICE_ADDR: "custom-inference-service:8080"
  FAQ_W2V_SERVICE_ADDR: "wordtovecservice:8080"
  FAQ_W2V_TIMEOUT: "1000"
  FAQ_RULE_SERVICE_URL: ""
  FAQ_SOLR_SERVICE_ADDR: "solr:8983"
  FAQ_SOLR_CANDIDATE_LIMIT: "30"
  FAQ_SOLR_TIMEOUT: "500"
  FAQ_SOLR_CORE: "3rd_core"
  FAQ_SOLR_DATABASE: "appId_other"
  FAQ_RANKER_ML_THRESHOLD: "98"
  FAQ_RANKER_QQ_THRESHOLD1: "80"
  FAQ_RANKER_QQ_THRESHOLD2: "65"
  FAQ_RANKER_QQ_THRESHOLD3: "50"
  FAQ_RANKER_QQ_EXTRA_POINT: "5"
  FAQ_ANSWER_THRESHOLD: "65.0"
  FAQ_FINAL_TOP: "5"
  FAQ_ML_SWITCH: "false"
  FAQ_RULE_SWITCH: "false"
  FAQ_MRULE_SWITCH: "false"
  FAQ_RULE_STACK: "[]"

# ==================================================================
# emotibot-controller20
# ==================================================================

  SYSTEM_TIME_ZONE: "Asia/Shanghai"
# 0 - debug : 3 - error
  MODULE_LOG_LEVEL: "0"
  EC_LOGGER_FILE_DIR: "/var/log/EmotibotController2.0"
  EC_HOST_LOGGER_FILE_DIR: "/tmp/log/EmotibotController2.0"
  EC_LOGGER_FILE_LOG_LEVEL: "DEBUG"
  EC_CONFIG_PATH: "/usr/src/app/config/WorkflowController.xml"
  EC_SERVER_PORT: "8080"
  EC_THREADPOOL_MAXTHREADS: "100"
  EC_THREADPOOL_MINTHREADS: "20"
  EC_SERVICE_TIMEOUT: "10"
  EC_FAQ_URL: "http://faq-module-20:8080"
  EC_EMOTION_URL: "http://emotion-support:8080/mood"
  EC_FUNCTION_INTENT_URL: "http://function-intent:8080/intent"
  EC_INTENT_URL: "http://intent-support:8080/intent"
  EC_CHAT_URL: "http://chat-service:8080/chat"
  EC_TASK_ENGINE_URL: "http://task-engine:8080/task_engine/ET"
  EC_NLU_SERVCIE_URL: "http://snlu-all:8080"
  EC_FUNCTION_URL: "http://function-web-service:8080/function/post"
  EC_PINYIN_SERVCIE_URL: ""
  EC_CONSUL_HOST: "consul:8500"
  EC_CONSUL_KEY_PREFIX: "idc/"
  EC_REDIS_HOST: "redis"
  EC_REDIS_PORT: "6379"
  EC_REDIS_PASSWORD: "syY6OUr8L2Y9bmAapWkZcw=="
  EC_REDIS_CONNECTION_TIMEOUT: "50"
  EC_EMOTION_THRESHOLD_1: "80"
  EC_RANKER_FAQ_THRESHOLD0: "85"
  EC_RANKER_FAQ_THRESHOLD1: "73"
  EC_RANKER_FAQ_THRESHOLD2: "65"
  EC_RANKER_CHAT_THRESHOLD: "40"
  EC_APPLICATION_CONTEXT_PATH: "file:/usr/src/app/config/applicationContext.xml"

  EC_MYSQL_EMOTIBOT_URL: "jdbc:mysql://mysql:3306/emotibot?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false"
  EC_MYSQL_EMOTIBOT_USERNAME: "root"
  EC_MYSQL_EMOTIBOT_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="
  EC_MYSQL_EMOTIBOT_INITIALSIZE: "1"
  EC_MYSQL_EMOTIBOT_MINIDLE: "1"
  EC_MYSQL_EMOTIBOT_MAXIDLE: "1"
  EC_MYSQL_EMOTIBOT_MAXTOTAL: "3"
  EC_MYSQL_BACKEND_LOG_URL: "jdbc:mysql://mysql:3306/backend_log?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false"
  EC_MYSQL_BACKEND_LOG_USERNAME: "root"
  EC_MYSQL_BACKEND_LOG_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="
  EC_MYSQL_BACKEND_LOG_INITIALSIZE: "2"
  EC_MYSQL_BACKEND_LOG_MINIDLE: "3"
  EC_MYSQL_BACKEND_LOG_MAXIDLE: "5"
  EC_MYSQL_BACKEND_LOG_MAXTOTAL: "20"

  #for minsheng
  EC_ENCRYPT_KEY: "eqwqrtfq5er"
  EC_ENCRYPT_SWITCH: "true"

# ==================================================================
# snlu-all 
# ==================================================================
  SNLU_WEB_PORT: "8080"
  SNLU_SENTENCE_TYPE_SERVICE_URL: "http://sentence-type:8080/getType"
  SNLU_SPEECH_ACT_SERVICE_URL: "http://speechact:10201/query"
  SNLU_SRL_SERVICE_URL: "http://172.17.0.1:12401/SRL"
  SNLU_DICT_DIR: "/home/deployer/thirdparty"
  SNLU_ENTITY_LINK_URL: "http://172.17.0.1:11002/"
  SNLU_DISQUE_HOST: "172.17.0.1"
  SNLU_DISQUE_PORT: "13902"
  SNLU_NUM_WORKER_THREAD: "10"
  SNLU_CONSUL_SERVICE_URL: "consul:8500/"
  SNLU_CONSUL_SERVICE_KEY: "idc/cnlu"
  SNLU_STATSD_HOST: "172.17.0.1"
  SNLU_STATSD_PORT: "8125"
  SNLU_STATSD_NAMESPACE: "emotibot"
  SNLU_PARSER_LIMIT: "2000"
  SNLU_SENTENCE_LIMIT: "50"
# ==================================================================
# solr-etl-agent 
# ==================================================================
  SEA_CONFIG_SERVER_HOST: "consul"
  SEA_CONFIG_SERVER_PORT: "8500"
  SEA_BASE_CORE: "merge_6_25"
  SEA_CUSTOMER_CORE: "3rd_core"
  SEA_VOLUME_PATH: "/home/deployer/debug_logs/solr-etl-agent"

# ==================================================================
# wordtovecservice 
# ==================================================================
  RCWV_MODEL_PATH: "/home/deployer/data/word2vec_model/vectors.bin"
  RCWV_SPORT_MODEL_PATH: "/home/deployer/data/word2vec_model/vectors.fastsent.bin"
  RCWV_SOLR_ADDR: ""
  RCWV_PORT: "8080"
  RCWV_MAX_THREAD: "100"

# ==================================================================
# custom-inference-service
# ==================================================================
  CIS_PORT: "8080"
  CIS_WOKER: "8"
  CIS_NATIVE_MODE: "True"
  CIS_UPDATE_INTERVAL: "15"
  CIS_LOG_LEVEL: "INFO"
  CIS_HOST_LOGGER_FILE_DIR: "/home/deployer/debug_logs/logs"
  CIS_TRADITIONAL_TO_SIMPLIFIED: "False"

# ==================================================================
# chat-service 
# ==================================================================
  CHAT_NAME: "chat_service"
  CHAT_PORT: "8080"
  CHat_MAX_OBJ_POOL: "50"
  CHat_MAX_THREAD_POOL: "10"
  CHat_MAX_TIMEOUT: "3200"
  CHat_MAX_MODULE_TIMEOUT: "3000"
  CHAT_FLOW_CONF: "controller-flow.conf"
  CHAT_IR_SOLR_EDIT_BASE: "solr:8983/solr"
  CHAT_IR_SOLR_EDIT_CORE: "3rd_core"
  CHAT_IR_SOLR_EDIT_DATABASE: "(appId_robot or chat)"
  CHAT_IR_SOLR_EDIT_CANDIDATE: "30"
  CHAT_IR_SOLR_EDIT_TOP: "5"
  CHAT_IR_W2V_BASE: "wordtovecservice:8080"
  CHAT_IR_QA_BASE: "answer-classifier:8080"
  CHAT_LOGGER_FILE_DIR: "/var/logs"
  CHAT_HOST_LOGGER_FILE_DIR: "/home/deployer/debug_logs/logs/controller_logs"
  CHAT_IR_NLP_SERV_ADDR: "snlu-all:8080"
# ==================================================================
# task-engine 
# ==================================================================
  TE_DOCKER_PORT: "8080"
  TE_REDIS_SERVER_DEFAULT: "redis"
  TE_REDIS_PORT_DEFAULT: "6379"
  TE_REDIS_EXPIRE_TIME: "100"
  TE_REDIS_PASSWORD: "syY6OUr8L2Y9bmAapWkZcw=="
  TE_LOG_VERBOSE: "INFO"
  TE_LOG_CONSUL_VERBOSE: "INFO"
  TE_HOST_LOG_PATH: "/home/deployer/debug_logs/task-engine"
  TE_LOG_PATH: "/usr/src/app/log/"
  TE_TIMEOUT: "20"
  TE_WORKERS: "20"
  TE_SCENARIO_FILE: "scenario_ctrip_bamboo.json"
  TE_MONGODB_URI: "172.17.0.1"
  TE_MONGODB_PORT: "27017"
  TE_MONGODB_DATABASE: "task_engine"
  TE_MYSQL_DB_USER: "root"
  TE_MYSQL_DB_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="
  TE_MYSQL_DB_SERVER: "mysql:3306"
  TE_LOAD_SCENARIO_FROM_DB: "mysqldb"
  TE_CONFIG_SERVER: "http://consul:8500/"
  TE_CONFIG_INTERVAL: "5"
  TE_CONFIG_KEY: "idc/te/scenario"
  TE_CONFIG_KEY_SCENARIO_ALL: "idc/te/scenario_all"
  TE_CONFIG_KEY_MAPPING_TABLE: "idc/te/mapping_table"
  TE_CONFIG_KEY_MAPPING_TABLE_ALL: "idc/te/mapping_table_all"
  TE_CONFIG_KEY_APPID_TO_SCENARIOID: "idc/te/app/"

  TE_PARSER_SERVICE_URL: "http://172.17.0.1:14701/parser"
  TE_TASK_PARSER_SERVICE_URL: "http://172.17.0.1:12101/tags/parser"
  TE_CU_ENABLE: "false"
  TE_CU_URL: "http://172.17.0.1:10701/cu"
  TE_COMMON_PARSER_SERVICE_URL: "http://common-parser-service:8080/common-parser-service"
  TE_QQ_SIMILARITY_SERVICE_URL: "http://wordtovecservice:8080/qq_similarity"


# ==================================================================
# sentence-type
# ==================================================================
  ST_SERVICE_PORT: "8080"

# ==================================================================
# wordtovecservice
# ==================================================================
  RCWV_MODEL_PATH: "/home/deployer/data/word2vec_model/vectors.bin"
  RCWV_SPORT_MODEL_PATH: "/home/deployer/data/word2vec_model/vectors.fastsent.bin"
  RCWV_MAX_THREAD: "100"

# ==================================================================
# admin-ui (houta + admin-api) 
# ==================================================================
  ADMIN_HT_FILE_PATH: "/home/deployer/backend_logs/"
  ADMIN_HT_DEBUG_PATH: "/home/deployer/debug_logs/logs/"
  ADMIN_HT_WEATHER: "http://172.17.0.1:10101/V2/weather?city_name="
  ADMIN_HT_WEB_PATH_API: "http://172.17.0.1/"
  ADMIN_HT_SETTING_API: "http://multicustomer:8080/robot_config?app_id="
  ADMIN_HT_PROCESS: "http://multicustomer:8080/process_data?app_id="
  ADMIN_HT_MANUAL_EDIT: "http://multicustomer:8080/manual_edit?app_id="
  ADMIN_HT_ENTITY: "http://multicustomer:8080/entity?app_id="
  ADMIN_HT_BUSINESS: "http://multicustomer:8080/business?app_id="
  ADMIN_HT_BUSINESS_DOWNLOAD: "http://multicustomer:8080/download?app_id="
  ADMIN_HT_BUSINESS_MANUAL: "http://multicustomer:8080/manual_business?app_id="
  ADMIN_HT_INTENT_BACKFILL: "http://multicustomer:8080/"
  ADMIN_HT_TASK_ENGINE: "http://bot-factory-backend-service:8080/"

  ADMIN_HT_DB_HOST: "mysql:3306"
  ADMIN_HT_DB_NAME: "emotibot"
  ADMIN_HT_DB_ACCOUNT: "root"
  ADMIN_HT_DB_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="

  ADMIN_HT_AUDIT_DB_HOST: "mysql:3306"
  ADMIN_HT_AUDIT_DB_NAME: "emotibot"
  ADMIN_HT_AUDIT_DB_ACCOUNT: "root"
  ADMIN_HT_AUDIT_DB_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="

  ADMIN_HT_INDEX_PATH: "VipAdmin/login.html"
  ADMIN_HT_MEDIABASE_MYSQL_URL: "mysql:3306"
  ADMIN_HT_MEDIABASE_MYSQL_USER: "root"
  ADMIN_HT_MEDIABASE_MYSQL_PASS: "b/ixGYSvx8c9bmAapWkZcw=="
  ADMIN_HT_MEDIABASE_MYSQL_DB: "emotibot"

# For run.sh use
  ADMIN_HTTP_PORT: "80"
# go global env
  ADMIN_SERVER_PORT: "8181"
  ADMIN_SERVER_AUTH_URL: "http://127.0.0.1:8088/auth/v2/token"
  ADMIN_SERVER_MYSQL_URL: "mysql:3306"
  ADMIN_SERVER_MYSQL_USER: "root"
  ADMIN_SERVER_MYSQL_PASS: "b/ixGYSvx8c9bmAapWkZcw=="
  ADMIN_SERVER_MYSQL_DB: "emotibot"
  ADMIN_SERVER_AUDIT_MYSQL_URL: "mysql:3306"
  ADMIN_SERVER_AUDIT_MYSQL_USER: "root"
  ADMIN_SERVER_AUDIT_MYSQL_PASS: "b/ixGYSvx8c9bmAapWkZcw=="
  ADMIN_SERVER_AUDIT_MYSQL_DB: "emotibot"
  ADMIN_SERVER_MC_URL: "http://multicustomer:8080"
  ADMIN_SERVER_CONSUL_URL: "http://consul:8500/v1/kv/idc/"
  ADMIN_SERVER_MOUNT_PATH: "/build/dist/Files"
  ADMIN_SERVER_SETTING_PATH: "/tmp/Files/settings"
  ADMIN_SERVER_LOG_LEVEL: "TRACE"
  ADMIN_QA_TEST_URL: "http://172.17.0.1:10901/robot"

  ADMIN_STATISTIC_MYSQL_URL: "mysql:3306"
  ADMIN_STATISTIC_MYSQL_USER: "root"
  ADMIN_STATISTIC_MYSQL_PASS: "b/ixGYSvx8c9bmAapWkZcw=="
  ADMIN_STATISTIC_MYSQL_DB: "backend_log"

  ADMIN_TASK_SERVER_URL: "http://bot-factory-backend-service:8080"
  ADMIN_STAT_SERVER_URL: "bot-factory-backend-service:8080"

  ADMIN_QA_CONTROLLER_URL: "http://emotibot-controller-20:8080/QAtest"
  ADMIN_QA_TEST_TYPE: "CONTROLLER"


  ADMIN_AUTH_MYSQL_URL: "mysql:3306"
  ADMIN_AUTH_MYSQL_USER: "root"
  ADMIN_AUTH_MYSQL_PASS: "b/ixGYSvx8c9bmAapWkZcw=="
  ADMIN_AUTH_MYSQL_DB: "authentication"
  ADMIN_AUTH_PORT: "8088"
  ADMIN_AUTH_CONSUL_URL: "consul:8500"

  ADMIN_AUDIT_MYSQL_URL: "mysql:3306"
  ADMIN_AUDIT_MYSQL_USER: "root"
  ADMIN_AUDIT_MYSQL_PASS: "b/ixGYSvx8c9bmAapWkZcw=="
  ADMIN_AUDIT_MYSQL_DB: "emotibot"

  ADMIN_ROBOT_SOLR_URL: "http://solr:8983/solr/3rd_core/select?q=(database:appid_robot OR database:chat)"
  ADMIN_DICTIONARY_INTERNAL_SERVER: "http://admin-ui:8080"
# ==================================================================
# bot-factory-backend-service
# ==================================================================
  BFB_PORT: "8080"
  BFB_MYSQL_DB_SERVER: "mysql:3306"
  BFB_MYSQL_DB_USER: "root"
  BFB_MYSQL_DB_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="
  BFB_MONGO_SERVER: "172.17.0.1"
  BFB_MONGO_PORT: "27017"
  BFB_CONSUL_SERVER: "consul:8500/v1/kv/idc"
  BFB_CONSUL_KEY: "te/scenario"
  BFB_CONSUL_APP: "te/app"
  BFB_CONSUL_MAPPING_TABLE: "te/mapping_table"
  BFB_CONSUL_MAPPING_TABLE_ALL: "te/mapping_table_all"
  BFB_DATABASE_TYPE: "mysql"
  BFB_STATIC_MYSQL_DB_SERVER: "mysql:3306"
  BFB_STATIC_MYSQL_DB_USER: "root"
  BFB_STATIC_MYSQL_DB_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="
  BFB_STATIC_DFT_APPID: "csbot"
  
  BFB_FTP_HOST: "197.3.133.201"
  BFB_FTP_USER: "ainlu"
  BFB_FTP_PASS: "gM4WHRQ1mEk9bmAapWkZcw=="
  BFB_FTP_PATH: "/batch_handle_pfm/USP/Result/Org"
  BFB_FTP_FILE: "SLORG_XIAOSHOU-EXT.txt"
# ==================================================================
# robotwriter
# ==================================================================
  DOCKER_PORT: "8080"
  CONTENT_SERVER: "https://content.emotibot.com"
  CONTENT_KEY: "2WDGS5SCH68RWDLC76BI9J6CZEKJM5QM"

# ==================================================================
# function-web-service
# ==================================================================
  FWS_BIND_PORT: "8080"
  FWS_FUNCTION_CONFIG_DIR: "./"
  FWS_CU_WEB_URL: ""

  FWS_CONSUL_HOST: "consul:8500"
  FWS_CONSUL_PREFIX_KEY: "idc/"

  FWS_MYSQL_EMOTIBOT_URL: "jdbc:mysql://mysql:3306/emotibot?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false"
  FWS_MYSQL_EMOTIBOT_USERNAME: "root"
  FWS_MYSQL_EMOTIBOT_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="
  FWS_MYSQL_EMOTIBOT_INITIALSIZE: "1"
  FWS_MYSQL_EMOTIBOT_MINIDLE: "1"
  FWS_MYSQL_EMOTIBOT_MAXIDLE: "1"
  FWS_MYSQL_EMOTIBOT_MAXTOTAL: "2"

  FWS_MATCH_HOSTNAME: "robotwriter"
  FWS_MATCH_PORT: "8080"
  FWS_MATCH_BASE_URL: "/soccer"
  FWS_WEATHER_HOSTNAME: "robotwriter"
  FWS_WEATHER_PORT: "8080"
  FWS_WEATHER_BASE_URL: "/weather"
  FWS_DATETIME_HOSTNAME: "robotwriter"
  FWS_DATETIME_PORT: "8080"
  FWS_DATETIME_BASE_URL: "/timeinfo"
  FWS_HOROSCOPE_HOSTNAME: "172.17.0.1"
  FWS_HOROSCOPE_PORT: "12601"
  FWS_HOROSCOPE_BASE_URL: "/horoscope"
  FWS_OLYMPIC_HOSTNAME: "172.17.0.1"
  FWS_OLYMPIC_PORT: "12601"
  FWS_OLYMPIC_BASE_URL: "/olympic"
  FWS_JOKE_FILESERVER_HOSTNAME: "fileservice.shadow.emotibot.com"
  FWS_JOKE_FILESERVER_PORT: "13001"
  FWS_JOKE_FILESERVER_BASE_URL: "/resource"
  FWS_RECOMMEND_GET_TOPIC_HOSTNAME: "172.17.0.1"
  FWS_RECOMMEND_GET_TOPIC_PORT: "12501"
  FWS_RECOMMEND_GET_TOPIC_URL: "/hotnews"
  FWS_SING_GET_SONG_HOSTNAME: "172.17.0.1"
  FWS_SING_GET_SONG_PORT: "11802"
  FWS_SING_GET_SONG_URL: "/automatic-composition"
  FWS_MUSIC_GET_MEMORY_URL: "172.17.0.1:11201/memory/rest/query/get"
  FWS_RIDDLE_REDIS_IP: "redis"
  FWS_FUNC_NEWS_TOPIC_HOSTNAME: "172.17.0.1"
  FWS_FUNC_NEWS_MEMORY_HOSTNAME: "172.17.0.1"
  FWS_FUNC_NEWS_TOPIC_PORT: "10301"
  FWS_FUNC_NEWS_MEMORY_PORT: "11201"
  FWS_FUNC_CONTENT_HOST: "http://function-content:8080"
  FWS_FUNC_COOKBOOK_HTML5_PATH: "http://idc.emotibot.com/Files/cooking/info.php"
  FWS_FUNC_COOKBOOK_CONTENT_HOST: "http://172.17.0.1:14201/cb/V1/find"
  FWS_FUNC_STOCK_HTML5_PATH: "http://idc.emotibot.com/Files/stock/info.php"
  FWS_FUNC_REMIND_DB_HOST: "http://172.17.0.1/api/APP"
  FWS_FUNC_MOIVE_KNOWLEDGE_PORT: "11002"
  FWS_FUNC_MOIVE_KNOWLEDGE_HTTP: "172.17.0.1"
  FWS_MOVIE_GET_MEMORY_URL: "172.17.0.1:11201/memory/rest/query/post"
  FWS_CHNEGYU_GET_SOLITAIRE_URL: "http://172.17.0.1:12201/api/idiom-solitaire"
  FWS_MUSIC_GET_DATABASE_URL: "172.17.0.1:13201/search/music"
  FWS_COMMON_GET_INTENT_ZOO_URL: "172.17.0.1:14301"
  FWS_COMMON_GET_FILESERVER_URL: "fileservice.shadow.emotibot.com:13001/resource"
  FWS_COMMON_GET_NLP_FROM_CU_URL: "http://172.17.0.1:10801/cuservice/rest/nlp/pos"
  FWS_CONCERT_GET_DATABASE_URL: "http://172.17.0.1:13701/concertservice/search"
  FWS_COMMON_PARSER_URL: "http://common-parser-service:8080/common-parser-service"
  #FWS_EC_TASK_ENGINE_ADDR: "http://task-engine:8080/task_engine/ET"

# ==================================================================
# mysql
# ==================================================================
#  MYSQL_ROOT_PASSWORD: "b/ixGYSvx8c9bmAapWkZcw=="

# ==================================================================
# phpmyadmin
# ==================================================================
  PMA_HOST: "mysql"

# ==================================================================
# statisticsd daemon
# ==================================================================
  STATISTICSD_DB_HOST: "mysql:3306"
  STATISTICSD_DB_USER: "root"
  STATISTICSD_DB_PWD: "b/ixGYSvx8c9bmAapWkZcw=="
  STATISTICSD_DB_TABLE: "csbot_record"
  STATISTICSD_BACKENDB: "backend_log"
  STATISTICSD_MAINDB: "emotibot"
  STATISTICSD_APPID: "csbot"
  STATISTICSD_TRACEDAY: "30"
